/** 
 * ETW Style Map produces styles for the ETW weekly newsletter. 
 * 
 * For now, this is created by hand after tested everything using
 * template.css. 
 * 
 * Eventually this file should be generated by a script from the
 * template.css. 
 */

window.ETWStyleMap = {
  // 'h2' : 'color: red;',
  // 'h4' : 'color: blue;',
};